export type PolicySection = { heading?: string; paragraphs?: string[]; bullets?: string[] }

export type Policy = { slug: string; title: string; description: string; sections: PolicySection[] }

const contact = "Questions may be sent to info@firstiefirearms.com."

export const policies: Record<string, Policy> = {
  "refund-policy": {
    slug: "refund-policy", title: "Refund Policy", description: "Refund and cancellation terms for custom and commemorative Firstie Firearms products.",
    sections: [
      { paragraphs: ["Firstie Firearms LLC (“Firstie Firearms,” “we,” “us,” or “our”) manufactures and sells custom and commemorative firearms and related products. Because many of our products are customized, engraved, finished, or produced specifically for a particular customer, class, organization, or production series, our refund policy differs from that of a traditional retail store."] },
      { heading: "Order Cancellations", paragraphs: ["Orders may be cancelled within 48 hours of purchase for a full refund.", "After 48 hours, all custom firearm orders are non-refundable, including orders for customized, engraved, Cerakoted, serialized, personalized, class-specific, or commemorative firearms.", "Cancellation requests must be submitted by email to info@firstiefirearms.com. Please include the customer's name and order number. A cancellation request is considered received when the email is delivered to Firstie Firearms. Approved refunds will be issued to the original payment method.", "After the 48-hour cancellation period expires, the order is considered committed to procurement, customization, and production and may not be cancelled or refunded except where required by applicable law or expressly approved by Firstie Firearms."] },
      { heading: "Custom and Commemorative Firearms", paragraphs: ["Customized, engraved, Cerakoted, serialized, personalized, class-specific, or commemorative firearms are final sale after the 48-hour cancellation period.", "Because these products are manufactured or modified specifically for the applicable production series, they cannot generally be returned because a customer changes their mind."] },
      { heading: "Firearm Transfers and Background Checks", paragraphs: ["Firearms are shipped only to an appropriately licensed Federal Firearms Licensee (“FFL”) for lawful transfer to the recipient.", "The receiving dealer is responsible for completing all legally required transfer procedures, including ATF Form 4473 and any applicable background check.", "It is the customer's responsibility to ensure that the purchaser and intended recipient are legally eligible to receive the firearm."], bullets: ["fails or is denied a required background check;", "is legally prohibited from possessing the firearm;", "does not satisfy applicable age or residency requirements;", "provides incorrect information;", "does not complete the transfer; or", "is otherwise unable to lawfully receive the firearm."] },
      { heading: "Damaged or Incorrect Products", paragraphs: ["Customers should inspect the firearm or product at the receiving FFL before accepting transfer whenever reasonably possible.", "If an item arrives visibly damaged, materially different from the item ordered, or with an apparent manufacturing issue, contact Firstie Firearms promptly at info@firstiefirearms.com before completing the transfer when possible.", "Do not ship a firearm directly to Firstie Firearms without first receiving return instructions."] },
      { heading: "After a Firearm Has Been Transferred", paragraphs: ["Once a firearm has been legally transferred to the purchaser or recipient, returns are generally not accepted except where required by law or specifically authorized by Firstie Firearms.", "Warranty or manufacturing concerns discovered after transfer may be handled under the applicable Firstie Firearms limited warranty or original firearm manufacturer's warranty, depending on the nature of the issue.", "Nothing in this policy limits any rights that cannot legally be waived under applicable law."] },
    ],
  },
  "terms-and-conditions": {
    slug: "terms-and-conditions", title: "Terms & Conditions", description: "Terms governing purchases made from Firstie Firearms LLC.",
    sections: [
      { paragraphs: ["These Terms & Conditions govern purchases made from Firstie Firearms LLC through www.firstiefirearms.com.", "By placing an order, you agree to these Terms & Conditions."] },
      { heading: "1. Legal Eligibility", paragraphs: ["You are responsible for ensuring that you may legally purchase, possess, receive, and own the products you order.", "For handgun purchases, the person receiving the firearm from the transferring FFL must satisfy all applicable federal, state, and local age requirements.", "You represent that you are not prohibited from purchasing or possessing firearms under applicable law."] },
      { heading: "2. Federal Firearms Licensee Transfer Required", paragraphs: ["Firearms purchased through Firstie Firearms are not shipped directly to the purchaser's residence unless expressly permitted by applicable law.", "Firearms requiring an FFL transfer are shipped to an appropriately licensed Federal Firearms Licensee selected or approved by the customer.", "The receiving dealer must complete all legally required transfer procedures before releasing the firearm, which may include verification of identity and residency, ATF Form 4473, NICS procedures or an applicable state alternative, waiting periods, permits or licenses, state or local documentation, and other applicable requirements.", "The receiving FFL has independent responsibility for determining whether a transfer may lawfully be completed."] },
      { heading: "3. Accuracy of Information", paragraphs: ["Customers agree to provide accurate information when placing an order.", "Providing false or misleading information regarding the purchaser, intended recipient, shipping destination, FFL, residency, eligibility, or other material information may result in cancellation of the order.", "Firstie Firearms will not knowingly participate in an unlawful firearm transfer or straw purchase."] },
      { heading: "4. State and Local Restrictions", paragraphs: ["Firearm, magazine, accessory, and configuration laws vary by jurisdiction.", "Firstie Firearms reserves the right to refuse or cancel an order, modify a configuration where permitted and agreed upon, substitute a state-compliant magazine or configuration, or decline to ship a product when we reasonably believe the transaction or product would violate applicable law.", "The customer remains responsible for complying with laws applicable to the customer's jurisdiction."] },
      { heading: "5. Custom Products", paragraphs: ["Many Firstie Firearms products contain custom engraving, finishing, Cerakote, artwork, commemorative markings, class insignia, or other modifications. Orders may be cancelled within 48 hours of purchase for a full refund. After 48 hours, custom firearm orders are non-refundable except where required by applicable law or expressly approved by Firstie Firearms."] },
      { heading: "6. Product Images", paragraphs: ["We make reasonable efforts to accurately display our products. Because firearms may include custom engraving, coatings, finishes, natural variations, manufacturing variations, and individually processed components, minor differences may exist between website photographs and the finished product. Such minor variations do not constitute a defect."] },
      { heading: "7. Pricing", paragraphs: ["Prices displayed on the website are shown in U.S. dollars unless otherwise indicated. Applicable taxes, shipping charges, transfer fees, or other charges may be added as appropriate. Prices and product availability may change without notice before an order is completed."] },
      { heading: "8. Payment", paragraphs: ["Payment is due according to the terms presented during checkout. Payment authorization does not guarantee that an order will be accepted or fulfilled. Firstie Firearms reserves the right to cancel and refund an order if the order cannot lawfully or reasonably be fulfilled."] },
      { heading: "9. Receiving FFL Fees", paragraphs: ["Any transfer fee, background-check fee, storage fee, permit fee, or other charge assessed by the receiving FFL is separate from the amount paid to Firstie Firearms unless specifically stated otherwise. The customer is responsible for those charges."] },
      { heading: "10. Refused or Abandoned Transfers", paragraphs: ["Customers are responsible for completing the FFL transfer in a timely manner. If a firearm is refused, abandoned, or cannot legally be transferred, the customer is responsible for coordinating with Firstie Firearms and the receiving FFL regarding lawful disposition. Additional shipping, storage, return, or administrative charges may apply. Customized firearms may not qualify for a refund."] },
      { heading: "11. Safety", paragraphs: ["Firearms are inherently dangerous products if mishandled. Purchasers and users are responsible for following the manufacturer's instructions, treating every firearm as loaded, keeping firearms pointed in a safe direction, keeping fingers away from the trigger until ready to fire, using appropriate ammunition, safely storing firearms away from unauthorized persons and children, obtaining appropriate training, and complying with all applicable firearm laws."] },
      { heading: "12. Warranty", paragraphs: ["Products may be covered by a Firstie Firearms limited warranty, an original manufacturer's warranty, or both, depending on the product and issue involved. Unauthorized modification, misuse, improper ammunition, improper maintenance, accidents, neglect, or modification by third parties may affect warranty coverage."] },
      { heading: "13. Limitation of Liability", paragraphs: ["To the maximum extent permitted by applicable law, Firstie Firearms will not be responsible for indirect, incidental, special, or consequential damages resulting from the misuse, unlawful possession, improper storage, unauthorized modification, or unsafe operation of a firearm. Nothing in these Terms & Conditions excludes liability that cannot legally be excluded or limited."] },
      { heading: "14. Changes to These Terms", paragraphs: ["Firstie Firearms may update these Terms & Conditions periodically. The version posted on the website at the time an order is placed will generally govern that transaction."] },
      { heading: "15. Contact", paragraphs: [contact] },
    ],
  },
  "shipping-policy": { slug: "shipping-policy", title: "Shipping Policy", description: "Shipping requirements for firearms and related products.", sections: [
    { paragraphs: ["Firstie Firearms ships firearms and related products in accordance with applicable federal, state, and local laws."] },
    { heading: "Firearm Shipments", paragraphs: ["Firearms requiring a dealer transfer are shipped only to an appropriately licensed Federal Firearms Licensee (“FFL”). A firearm will not be shipped until Firstie Firearms has received and verified the information necessary for the receiving FFL. Customers may be asked to provide the dealer's business name, address, telephone number, email address, and/or Federal Firearms License information. Firstie Firearms may contact the receiving dealer directly to verify licensing information."] },
    { heading: "Customer Responsibility", paragraphs: ["The customer is responsible for selecting an FFL that is willing to receive and transfer the firearm. We strongly recommend contacting the dealer before placing or completing an order to confirm that the dealer accepts transfers from Firstie Firearms, will transfer the specific firearm or configuration, and has informed the customer of transfer fees or local requirements."] },
    { heading: "Shipping Address", paragraphs: ["For firearm purchases, the shipping address used for the firearm will generally be the verified premises address of the receiving FFL rather than the customer's residential address. Firearms cannot be shipped to a P.O. Box."] },
    { heading: "Shipping Charges", paragraphs: ["Applicable shipping charges are displayed during checkout or otherwise disclosed as part of the order. Any receiving-FFL transfer fee is separate and is paid directly to the receiving dealer unless specifically stated otherwise."] },
    { heading: "Shipping Restrictions", paragraphs: ["We do not knowingly ship firearms, magazines, or regulated products into jurisdictions where the applicable product is prohibited. Some states or localities may require alternative magazines, product configurations, permits, documentation, or other accommodations. Firstie Firearms reserves the right to delay, modify with customer approval, or cancel an order if necessary to comply with applicable law."] },
    { heading: "Tracking", paragraphs: ["When available, shipment tracking information will be provided after the order has shipped. For security reasons, firearm deliveries may be subject to carrier requirements and must be received by the licensed dealer."] },
    { heading: "Shipping Damage", paragraphs: ["If a shipment appears damaged when received by the FFL, the customer should contact Firstie Firearms promptly at info@firstiefirearms.com. Whenever possible, customers should inspect the firearm with the receiving dealer before accepting the transfer."] },
  ] },
  "delivery-timeframe": { slug: "delivery-timeframe", title: "Delivery Timeframe", description: "Production and delivery estimates for custom and commemorative firearms.", sections: [
    { paragraphs: ["Firstie Firearms specializes in custom and commemorative firearms. These products may require engraving, finishing, Cerakote, assembly, inspection, packaging, and other production work before shipment. They should therefore not be considered immediately available retail inventory unless specifically described that way on the applicable product page."] },
    { heading: "Production Schedule", paragraphs: ["Firstie Firearms generally manufactures commemorative firearms in scheduled production batches. The estimated delivery or production window applicable to a particular series will be displayed on the applicable product page, ordering materials, or order confirmation.", "Unless otherwise stated for a particular product, custom firearm orders are generally expected to ship approximately 4–8 weeks after the applicable production/order batch closes. Because customers may place an order before the applicable production batch closes, the total period between the date an order is placed and the date it ships may be longer."] },
    { heading: "When the Delivery Period Begins", paragraphs: ["An order may not be ready for shipment until payment has been successfully processed, required customization selections have been received, production and quality-control inspection have been completed, required receiving-FFL information has been received and verified, and the firearm can lawfully be shipped to the destination. Failure to provide required FFL or customer information may delay shipment."] },
    { heading: "Estimated Dates", paragraphs: ["Any production, shipping, or delivery date provided by Firstie Firearms is a good-faith estimate unless we expressly state that the date is guaranteed. Custom manufacturing can be affected by component availability, engraving or finishing schedules, manufacturer delays, regulatory requirements, carrier delays, and other circumstances outside our reasonable control. If a material delay occurs, Firstie Firearms will make reasonable efforts to communicate an updated estimated timeframe."] },
    { heading: "Delivery Means Delivery to the FFL", paragraphs: ["For firearms requiring an FFL transfer, “delivery” generally means delivery of the firearm to the receiving licensed dealer. It does not mean that the firearm will immediately be released to the purchaser. The purchaser must still complete the legally required transfer process with the receiving FFL. Background-check delays, waiting periods, permits, dealer operating hours, local requirements, or other transfer requirements can affect when the customer may take possession after the firearm arrives at the FFL."] },
    { paragraphs: [contact] },
  ] },
}

export const policySlugs = Object.keys(policies)
